### ISSUE TITLE
Credit original author

### ISSUE THREAD

**Issue by TedDriggs** [TedDriggs/serde_case#1]
After looking at serde's PRs, @46bit was the original author of this code. @46bit - would you like to be credited as an author of this crate in Cargo.toml?

**Comment by 46bit** [comment]
Hey Ted,

Nah, don't worry about it. If you're building this just to get conversions, libraries (of varying quality) already exist - e.g., https://crates.io/crates/inflector. But either way, all the best.

**Comment by TedDriggs** [comment]
I'm working on a crate specifically for proc macros, so having just serde's piece (and exactly matching serde's behavior) was very useful. Thanks for replying; inflector does look very cool for general use.
