### ISSUE TITLE
Trying to understand what this crate is for

### ISSUE THREAD

**Issue by elichai** [TedDriggs/serde_case#2]
Hi,
shouldn't This work?
```
assert_eq!(&RenameRule::PascalCase.apply_to_field("TEST"), "Test");
```

**Comment by TedDriggs** [comment]
`apply_to_field` assumes that it's being passed in a snake_case field, so it just looks for underscores and replaces them with capitals. This crate's API came from serde's internals, but I'm not sure that I love the API. I mostly use it because it's well-tested by `serde`.
